[project]
name = "less-go"
version = "0.1.0"
description = "For help!"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "discord.py>=2.4.0",
    "aiohttp>=3.10.0",
    "python-dotenv>=1.0.1",
]
